[automount]
enabled=true
mountFsTab=true
root=/mnt/

[network]
generateHosts=true
generateResolvConf=true
hostname=bi7dyv

[interop]
enabled=true
appendWindowsPath=true

[user]
default=greenpia

[boot]
systemd=true
command=ip link set dev eth0 mtu 1200
protectBinfmt=true

[gpu]
enabled=true

[time]
useWindowsTimezone=true
